package com.matrix.user_task;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CharsetUtil implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public CharsetUtil() {
    }

}