package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Order implements java.io.Serializable {

    static final long serialVersionUID = 6L;

    public Order() {
    	
    }

    
}
