package com.matrix.multiple_instance_human_task;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Order implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "orderId")
   private int orderId;
   @org.kie.api.definition.type.Label(value = "description")
   private java.lang.String description;

   public Order()
   {
   }

   public int getOrderId()
   {
      return this.orderId;
   }

   public void setOrderId(int orderId)
   {
      this.orderId = orderId;
   }

   public java.lang.String getDescription()
   {
      return this.description;
   }

   public void setDescription(java.lang.String description)
   {
      this.description = description;
   }

   public Order(int orderId, java.lang.String description)
   {
      this.orderId = orderId;
      this.description = description;
   }

}