package com;


import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Utils implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Utils() {
    }

    public static void writeTextFile(final String pathName,
            final String fileName, String line) {

        PrintWriter printWriter = null;
        File file = null;
        try {
            File dir = new File(pathName);
            if (!dir.exists()) {
                dir.mkdirs();
            }
            dir = null;

            file = new File(pathName + File.separator + fileName);
            if (file.exists()) {
                file.delete();
            }

            printWriter = new PrintWriter(file);

            printWriter.println(line);
        } catch (final Exception e) {
            e.printStackTrace();
        }

        if (printWriter != null) {
            printWriter.close();
        }
    }
    
}